/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.24 from the
 * contents of XS.xs. Do not edit this file, edit XS.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "XS.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "const-c.inc"

typedef struct { 
    int** cell; 
    int heigth; 
    int width;
} MATRIX;

#line 26 "XS.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 168 "XS.c"

/* INCLUDE:  Including 'const-xs.inc' from 'XS.xs' */


XS_EUPXS(XS_MMultiplier__XS_constant); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MMultiplier__XS_constant)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	/* IV		iv;	Uncomment this if you need to return IVs */
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 193 "XS.c"
	SV *	sv = ST(0)
;
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
	type = constant(aTHX_ s, len);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid MMultiplier::XS macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined MMultiplier::XS macro %s, used",
				   s));
          PUSHs(sv);
          break;
	/* Uncomment this if you need to return IVs
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break; */
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing MMultiplier::XS macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 270 "XS.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'XS.xs' from 'const-xs.inc' */


XS_EUPXS(XS_MMultiplier__XS_doIt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_MMultiplier__XS_doIt)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "A, B");
    {
	MATRIX *	RETVAL;
	MATRIX *	A;
	MATRIX *	B;

	{
		int checkpoint = PL_sv_count;
		if (!SvOK(ST(0)) || !SvROK(ST(0))) croak("Ref?");
		AV *tm__p = (AV*)SvRV(ST(0));
		if (SvTYPE(tm__p)!=SVt_PVAV) croak("Not ARRAY");
		AV* tm_p = (AV*)tm__p;

		MATRIX * m = malloc(sizeof(MATRIX));
		SV **first =  av_fetch (tm_p, 0, 0);
		// sv_dump(tm_p);
		if ( ! ( SvOK(*first) && SvROK(*first) && SvTYPE(SvRV(*first)) == SVt_PVAV ) ) croak("arg must be arref of arref111");

		AV *inner = (AV*)SvRV(*first);

		int heigth = av_len(tm_p); // av_len is not length but last index!!!
		int width = av_len(inner);
		m->heigth = heigth+1;
		m->width = width+1;
		// printf("h: %d \nw: %d\n",m->heigth, m->width);
		m->cell = (int**)malloc(heigth * sizeof(int*));
		for (int i =0; i <= heigth; ++i) {
			SV **_next =  av_fetch (tm_p, i, 0);
			if ( ! (SvOK(*_next) && SvROK(*_next) && SvTYPE(SvRV(*_next)) == SVt_PVAV ) ) croak("arg must be arref of arref");
			AV *next = (AV*)SvRV(*_next);
			if (av_len(next) != width) croak("matrix must be rectangular ", av_len(next)," ", width);
			m->cell[i] = (int*)malloc(width * sizeof(int));

			for (int j = 0; j <= width; ++j) {
				SV **_value =  av_fetch (next, j, 0);
				if(!SvOK(*_value)) croak("cant fill the matrix");
				m->cell[i][j] = SvIV(*_value);
				// printf("%d ", m->cell[i][j]);
			}
			// printf("\n");
		}
		A = (MATRIX *)m;
	}
;

	{
		int checkpoint = PL_sv_count;
		if (!SvOK(ST(1)) || !SvROK(ST(1))) croak("Ref?");
		AV *tm__p = (AV*)SvRV(ST(1));
		if (SvTYPE(tm__p)!=SVt_PVAV) croak("Not ARRAY");
		AV* tm_p = (AV*)tm__p;

		MATRIX * m = malloc(sizeof(MATRIX));
		SV **first =  av_fetch (tm_p, 0, 0);
		// sv_dump(tm_p);
		if ( ! ( SvOK(*first) && SvROK(*first) && SvTYPE(SvRV(*first)) == SVt_PVAV ) ) croak("arg must be arref of arref111");

		AV *inner = (AV*)SvRV(*first);

		int heigth = av_len(tm_p); // av_len is not length but last index!!!
		int width = av_len(inner);
		m->heigth = heigth+1;
		m->width = width+1;
		// printf("h: %d \nw: %d\n",m->heigth, m->width);
		m->cell = (int**)malloc(heigth * sizeof(int*));
		for (int i =0; i <= heigth; ++i) {
			SV **_next =  av_fetch (tm_p, i, 0);
			if ( ! (SvOK(*_next) && SvROK(*_next) && SvTYPE(SvRV(*_next)) == SVt_PVAV ) ) croak("arg must be arref of arref");
			AV *next = (AV*)SvRV(*_next);
			if (av_len(next) != width) croak("matrix must be rectangular ", av_len(next)," ", width);
			m->cell[i] = (int*)malloc(width * sizeof(int));

			for (int j = 0; j <= width; ++j) {
				SV **_value =  av_fetch (next, j, 0);
				if(!SvOK(*_value)) croak("cant fill the matrix");
				m->cell[i][j] = SvIV(*_value);
				// printf("%d ", m->cell[i][j]);
			}
			// printf("\n");
		}
		B = (MATRIX *)m;
	}
;
#line 22 "XS.xs"
    // printf("IN XS\n\n");
    // printf("%d %d\n%d %d",A->width, A->heigth,B->width, B->heigth);
    if(A->width != B->heigth) croak("only like this MATRIX A(m, p) * B(p, n) could be multiplied");

    MATRIX *C = malloc(sizeof(MATRIX));
    C->heigth = A->heigth;
    C->width = B->width;
    C->cell = (int**)malloc(C->heigth * sizeof(int*));
    for(int i = 0; i < C->heigth; ++i)
        C->cell[i] = (int*)malloc(C->width * sizeof(int));

    for (int i = 0; i < A->heigth; ++i) {
        for (int j = 0; j < B->width; ++j) {
            C->cell[i][j] = 0;
            for (int k =0; k < A->width; ++k) {
                C->cell[i][j] += A->cell[i][k] * B->cell[k][j];
            }
            // printf("%d ", C->cell[i][j]);
        }   
        // printf("\n");
    }


    RETVAL = C;
#line 393 "XS.c"
	ST(0) = sv_newmortal();
	{
		// in XS.c, ST 0 already mortal
		//	ST(0) = sv_newmortal();
		//RETVAL ST(0) MATRIX *
		// $var $arg $type

		// printf("%d\n", RETVAL->width);
		// printf("%d\n", RETVAL->heigth);
		AV *array = (AV*)newAV();
		for (int i = 0; i < RETVAL->heigth; i++) {
			AV *inner = (AV*)newAV();
			for (int j = 0; j < RETVAL->heigth; j++) {
				av_push(inner, (SV*)newSViv(RETVAL->cell[i][j]));
			}
			av_push(array, (SV*)newRV((SV*)inner));
			free(RETVAL->cell[i]);
		}
		free(RETVAL->cell);
		// sv_dump((SV*)array);
		sv_setsv(ST(0), (SV*)newRV_noinc((SV*)array));
	}
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_MMultiplier__XS); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_MMultiplier__XS)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("MMultiplier::XS::constant", XS_MMultiplier__XS_constant, file);
        newXS("MMultiplier::XS::doIt", XS_MMultiplier__XS_doIt, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

